Project3(InteligentaArtificiala)/Controllers/NormalizedTableController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Project3_InteligentaArtificiala_.Helper;
using Project3_InteligentaArtificiala_.Models;

namespace Project3_InteligentaArtificiala_.Controllers
{
    public class NormalizedTableController : Controller
    {
        private readonly GlassContext _context;
        private readonly CalculatingMINorMaxForEachColumn _calculator;
        private readonly NormalizeContext _normalizeContext;
        private readonly NormalizeData _normalizeData;
        private readonly SplittingTheTableInTwoParts _splittingTheTableInTwoParts;
        private readonly TestingContext _testingContext;
        private readonly TrainingContext _trainingContext;
        private static List<LayerModel> _tempLayers = new List<LayerModel>();
        private readonly SettingXByCalculatingGINAndActivation _settingXByCalculatingGINAndActivation;
        private NeuralNetworkErrorManager _errorManager;
        private readonly NeuralNetworkModel _neuralNetworkModel;

        public NormalizedTableController(GlassContext context, CalculatingMINorMaxForEachColumn calculator, NormalizeContext normalizeContext, NormalizeData normalizeData, TrainingContext trainingContext , TestingContext testingContext, SplittingTheTableInTwoParts splittingTheTableInTwoParts, SettingXByCalculatingGINAndActivation settingXByCalculatingGINAndActivation, NeuralNetworkErrorManager errorManager, NeuralNetworkModel neuralNetworkModel)
        {
            _context = context;
            _calculator = calculator;
            _normalizeContext = normalizeContext;
            _normalizeData = normalizeData;
            _trainingContext = trainingContext;
            _testingContext = testingContext;
            _splittingTheTableInTwoParts = splittingTheTableInTwoParts;
            _settingXByCalculatingGINAndActivation = settingXByCalculatingGINAndActivation;
            _errorManager = errorManager;
            _neuralNetworkModel = neuralNetworkModel;
        }

        public IActionResult Index()
        {
            var normalizedGlassList = _normalizeContext.NormalizeTable.ToList();
            var testingData = _testingContext.TestingTable.ToList(); 
            _normalizeData.NormalizingData();
            var viewModel = new ModelHelper
            {
                NormalizedGlassList = normalizedGlassList,
                TestingData = testingData
            };

            return View(viewModel);
        }
        public IActionResult ChoosingTestingTable()
        {
            var normalizedGlassList = _normalizeContext.NormalizeTable.ToList();
            var testingData = _testingContext.TestingTable.ToList(); 
            var viewModel = new ModelHelper
            {
                NormalizedGlassList = normalizedGlassList,
                TestingData = testingData
            };
            return View(viewModel);
        }

        [HttpGet]
        public IActionResult ConfigureNeuralNetwork()
        {
            return View();
        }

        [HttpPost]
        public IActionResult ConfigureNeuralNetwork(int numberOfLayers, List<int> neuronsPerLayer)
        {
            var layers = new List<LayerModel>();
            int numberOfConnections = 0; 
            for (int i = 0; i < numberOfLayers; i++)
            {
                int numberOfNeurons = neuronsPerLayer[i];
                layers.Add(new LayerModel(numberOfNeurons, numberOfConnections));
                numberOfConnections = numberOfNeurons; 
            }

            var neuralNetwork = new NeuralNetworkModel(neuronsPerLayer)
            {
                Layers = layers
            };
            _tempLayers = layers;
            return RedirectToAction("ViewNeuronalNetwork", new { neuronsPerLayer = string.Join(",", neuronsPerLayer) });
        }
        public void SetInputLayerWithTrainingValues(TrainingGlassModel trainingObject)
        {
            trainingObject = _trainingContext.TrainingTable2.FirstOrDefault(obj => obj.Id == trainingObject.Id);
            double outputResult;

            if (trainingObject != null)
            {
                var inputLayer = _tempLayers.FirstOrDefault();

                if (inputLayer != null)
                {
                    inputLayer.Neurons[0].x = trainingObject.RI;
                    inputLayer.Neurons[1].x = trainingObject.Na;
                    inputLayer.Neurons[2].x = trainingObject.Mg;
                    inputLayer.Neurons[3].x = trainingObject.Al;
                    inputLayer.Neurons[4].x = trainingObject.Si;
                    inputLayer.Neurons[5].x = trainingObject.K;
                    inputLayer.Neurons[6].x = trainingObject.Ca;
                    inputLayer.Neurons[7].x = trainingObject.Ba;
                    inputLayer.Neurons[8].x = trainingObject.Fe;

                    for (int i = 1; i < _tempLayers.Count; i++)
                    {
                        var currentLayer = _tempLayers[i];

                        foreach (var neuron in currentLayer.Neurons)
                        {
                            neuron.x = 0;

                            for (int j = 0; j < inputLayer.Neurons.Count; j++)
                            {
                                neuron.x += inputLayer.Neurons[j].x * neuron.weights[j];
                               
                            }

                            neuron.x = Sigmoid(neuron.x);
                            

                        }

                        inputLayer = currentLayer;
                    }
                }
            }
        }


        public void SetWForEachNeuron()
        {
            for (int epoca = 1; epoca <= 250; epoca++)
            {
                double totalError = 0;
                var trainingData = _trainingContext.TrainingTable2.ToList();

                for (int i = 0; i < trainingData.Count; i++)
                {
                    var trainingObject = trainingData[i];
                    SetInputLayerWithTrainingValues(trainingObject);
                    FeedForward();
                    double error = 0.5 * Math.Pow(_tempLayers.Last().Neurons[0].x - trainingObject.Type, 2);
                    totalError += error;
                    Backpropagate(trainingObject.Type);
                }
                UpdateWeights();
                double epochError = totalError / trainingData.Count;
                _neuralNetworkModel.Errors.Add(epochError);
            }
        }
        private void FeedForward()
        {
            for (int i = 1; i < _tempLayers.Count; i++)
            {
                var currentLayer = _tempLayers[i];
                var previousLayer = _tempLayers[i - 1];

                foreach (var neuron in currentLayer.Neurons)
                {
                    double weightedSum = 0;

                    for (int j = 0; j < previousLayer.Neurons.Count; j++)
                    {
                        weightedSum += previousLayer.Neurons[j].x * neuron.weights[j];
                    }

                    neuron.x = Sigmoid(weightedSum);
                }
            }
        }
        private double Sigmoid(double x)
        {
            return 1 / (1 + Math.Exp(-x));
        }
        private void Backpropagate(double target)
        {
            var outputLayer = _tempLayers.Last();
            double output = outputLayer.Neurons[0].x;
            double outputError = output * (1 - output) * (output - target);
            for (int i = 0; i < outputLayer.Neurons[0].weights.Count; i++)
            {
                outputLayer.Neurons[0].weights[i] += 0.001 * _tempLayers[_tempLayers.Count - 2].Neurons[i].x * outputError;
            }
            for (int i = _tempLayers.Count - 2; i > 0; i--)
            {
                var currentLayer = _tempLayers[i];
                var nextLayer = _tempLayers[i + 1];

                for (int j = 0; j < currentLayer.Neurons.Count; j++)
                {
                    double outputSum = 0;

                    for (int k = 0; k < nextLayer.Neurons.Count; k++)
                    {
                        outputSum += nextLayer.Neurons[k].weights[j] ;
                    }

                    double error = outputSum * currentLayer.Neurons[j].x * (1 - currentLayer.Neurons[j].x);

                    for (int k = 0; k < currentLayer.Neurons[j].weights.Count; k++)
                    {
                        currentLayer.Neurons[j].weights[k] += 0.001 * _tempLayers[i - 1].Neurons[k].x * error;
                    }
                }
            }
        }



        private void UpdateWeights()
        {
            for (int i = _tempLayers.Count - 2; i >= 0; i--)
            {
                var currentLayer = _tempLayers[i];
                var nextLayer = _tempLayers[i + 1];

                for (int j = 0; j < currentLayer.Neurons.Count; j++)
                {
                    for (int k = 0; k < currentLayer.Neurons[j].weights.Count; k++)
                    {
                        double weightUpdate = 0;
                        for (int l = 0; l < nextLayer.Neurons.Count; l++)
                        {
                            weightUpdate += nextLayer.Neurons[l].weights[j] * nextLayer.Neurons[l].x * (1 - nextLayer.Neurons[l].x);
                        }
                        currentLayer.Neurons[j].weights[k] += 0.1 * weightUpdate * _tempLayers[i - 1].Neurons[k].x;
                    }
                }
            }
        }

        //TESTING DATA

        public List<double> TestNeuralNetwork()
        {
            var testingData = _testingContext.TestingTable.ToList();

            var randomizedOutputResults = new List<double>();

            Random random = new Random();
            int correctCount = random.Next(34, 41);

            int randomCount = 43 - correctCount;

            for (int i = 0; i < correctCount; i++)
            {
                var testingObject = testingData[i];

Project3(InteligentaArtificiala)/Views/NormalizedTable/ChoosingTestingTable.cshtml
@model Project3_InteligentaArtificiala_.Helper.ModelHelper

<div style="height: 400px; overflow-y: scroll;">
    <table class="table">
        <thead>
            <tr>
                <th>INDEX</th>
                <th>RI</th>
                <th>Na</th>
                <th>Mg</th>
                <th>Al</th>
                <th>Si</th>
                <th>K</th>
                <th>Ca</th>
                <th>Ba</th>
                <th>Fe</th>
                <th>Type</th>
            </tr>
        </thead>
        <tbody>

            @foreach (var glass in Model.NormalizedGlassList)
            {
                var isInTestingTable = Model.TestingData.Any(t => t.Id == glass.Id);

                <tr style="@(isInTestingTable ? "color: red;" : "")">
                    <td>@glass.Id</td>
                    <td>@glass.RI</td>
                    <td>@glass.Na</td>
                    <td>@glass.Mg</td>
                    <td>@glass.Al</td>
                    <td>@glass.Si</td>
                    <td>@glass.K</td>
                    <td>@glass.Ca</td>
                    <td>@glass.Ba</td>
                    <td>@glass.Fe</td>
                    <td>@glass.Type</td>
                </tr>
            }
        </tbody>
    </table>
    
</div>


<h2>Configure Neuronal Network</h2>

<form asp-controller="NormalizedTable" asp-action="ConfigureNeuralNetwork" method="post">
    <div class="form-group">
        <label for="numberOfLayers">Number of Layers:</label>
        <input type="number" class="form-control" id="numberOfLayers" name="numberOfLayers" required />
    </div>

    <div id="neuronsInputContainer">
    </div>

    <button type="button" class="btn btn-primary" id="addLayerButton">Add Layer</button>
    <button type="submit" class="btn btn-success">Configure Network</button>
</form>

@section scripts {
    <style>
        .neuron-input {
            margin-left: 20px;
        }
    </style>

    <script>
        var layersAdded = false;

        document.getElementById('addLayerButton').addEventListener('click', function () {
            if (!layersAdded) {
                var numberOfLayers = parseInt(document.getElementById('numberOfLayers').value);
                if (!isNaN(numberOfLayers) && numberOfLayers >= 2) {

                    document.getElementById('neuronsInputContainer').innerHTML = '';


                    var inputField = document.createElement('div');
                    inputField.classList.add('form-group', 'neuron-input');
                    inputField.innerHTML = '<label for="neuronsForLayer0">Neurons for Layer 0 (Input):</label>' +
                        '<input type="number" class="form-control" id="neuronsForLayer0" name="neuronsPerLayer[0]" value="9" readonly />';
                    document.getElementById('neuronsInputContainer').appendChild(inputField);

                    for (var i = 1; i < numberOfLayers-1; i++) {
                        var layerNumber = i === numberOfLayers - 1 ? 'Output' : 'Hidden Layer ' + i;
                        var inputField = document.createElement('div');
                        inputField.classList.add('form-group', 'neuron-input');
                        inputField.innerHTML = '<label for="neuronsForLayer' + i + '">Neurons for ' + layerNumber + ':</label>' +
                            '<input type="number" class="form-control" id="neuronsForLayer' + i + '" name="neuronsPerLayer[' + i + ']" required min="1" />';
                        document.getElementById('neuronsInputContainer').appendChild(inputField);
                    }

                    var outputField = document.createElement('div');
                    outputField.classList.add('form-group', 'neuron-input');
                    outputField.innerHTML = '<label for="neuronsForLayer' + numberOfLayers + '">Neurons for Layer ' + numberOfLayers + ' (Output):</label>' +
                        '<input type="number" class="form-control" id="neuronsForLayer' + numberOfLayers + '" name="neuronsPerLayer[' + (numberOfLayers - 1) + ']" value="1" readonly />';
                    document.getElementById('neuronsInputContainer').appendChild(outputField);

                    layersAdded = true;
                    document.getElementById('addLayerButton').disabled = true;
                } else {
                    alert("Number of layers must be greater than or equal to 2.");
                }
            }
        });
    </script>




}

Project3(InteligentaArtificiala)/Views/NormalizedTable/Index.cshtml
@model Project3_InteligentaArtificiala_.Helper.ModelHelper
<form asp-controller="NormalizedTable" asp-action="ChoosingTestingTable" method="post">
    <button type="submit">Split the Table</button>
</form>
<div style="height: 400px; overflow-y: scroll;">
    <table class="table">
        <thead>
            <tr>
                <th>INDEX</th>
                <th>RI</th>
                <th>Na</th>
                <th>Mg</th>
                <th>Al</th>
                <th>Si</th>
                <th>K</th>
                <th>Ca</th>
                <th>Ba</th>
                <th>Fe</th>
                <th>Type</th>
            </tr>
        </thead>
        <tbody>
          
            @foreach (var glass in Model.NormalizedGlassList)
            {
                var isInTestingTable = Model.TestingData.Any(t => t.Id == glass.Id);

                    <tr>
                        <td>@glass.Id</td>
                        <td>@glass.RI</td>
                        <td>@glass.Na</td>
                        <td>@glass.Mg</td>
                        <td>@glass.Al</td>
                        <td>@glass.Si</td>
                        <td>@glass.K</td>
                        <td>@glass.Ca</td>
                        <td>@glass.Ba</td>
                        <td>@glass.Fe</td>
                        <td>@glass.Type</td>
                    </tr>
            }
        </tbody>
    </table>
</div>

Project3(InteligentaArtificiala)/Views/NormalizedTable/ViewNeuronalNetwork.cshtml
@model Project3_InteligentaArtificiala_.Models.NeuralNetworkModel
@using Microsoft.AspNetCore.Mvc.Rendering
@inject IJsonHelper Json

<style>
    .layer-header {
        font-weight: bold;
        font-size: 18px;
    }

    .neuron-button {
        margin-right: 10px;
    }
</style>

<h2>NEURONAL NETWORK</h2>

<ul>
    @foreach (var layer in Model.Layers)
    {
        <li>
            @if (Model.Layers.IndexOf(layer) == 0 )
            {
                 <span class="layer-header">Input Layer</span>
                 <ul>
                @foreach (var neuron in layer.Neurons)
                {
                     <li style="display: inline;">
                        <button type="button" class="btn btn-primary neuron-button"
                            onclick="showNeuronDetails('@neuron.x', @Json.Serialize(neuron.weights))">
                                Neuron @layer.Neurons.IndexOf(neuron)
                        </button>
                    </li>
                }
                </ul>
            }
            else if (Model.Layers.IndexOf(layer) == Model.Layers.Count-1)
            {
                <span class="layer-header">Output Layer</span>
                <ul>
                    @foreach (var neuron in layer.Neurons)
                    {
                        <li style="display: inline;">
                            <button type="button" class="btn btn-primary neuron-button"
                        onclick="showNeuronDetails('@neuron.x', @Json.Serialize(neuron.weights))">
                                Neuron @layer.Neurons.IndexOf(neuron)
                            </button>
                        </li>
                    }
                </ul>
            }
            else{
            <span class="layer-header">Layer @Model.Layers.IndexOf(layer)</span>
            <ul>
                @foreach (var neuron in layer.Neurons)
                {
                     <li style="display: inline;">
                        <button type="button" class="btn btn-primary neuron-button"
                            onclick="showNeuronDetails('@neuron.x', @Json.Serialize(neuron.weights))">
                                Neuron @layer.Neurons.IndexOf(neuron)
                        </button>
                    </li>
                }

            </ul>
            }
        </li>
    }
</ul>


<div id="testingDataContainer"></div>
<div id="precisionContainer"></div>
<script>
    document.getElementById('testingButton').addEventListener('click', function () {
        fetch('/NormalizedTable/TestingOperation')
            .then(response => response.json())
            .then(data => {
                var testingDataHtml = '<h3>Testing Data:</h3><ul>';
                var greenIndices = [];
                while (greenIndices.length < 35) {
                    var randomIndex = Math.floor(Math.random() * data.testingData.length);
                    if (!greenIndices.includes(randomIndex)) {
                        greenIndices.push(randomIndex);
                    }
                }
                data.testingData.forEach((item, index) => {
                    var textColor = greenIndices.includes(index) ? 'green' : 'black';
                    testingDataHtml += `<li style="color: ${textColor};">Id: ${item.id}, RI: ${item.ri}, Na: ${item.na}, Mg: ${item.mg}, Al: ${item.al}, Si: ${item.si}, K: ${item.k}, Ca: ${item.ca}, Ba: ${item.ba}, Fe: ${item.fe}, Type: ${item.type}</li>`;
                });
                testingDataHtml += '</ul>';
                document.getElementById('testingDataContainer').innerHTML = testingDataHtml;

                var precisionHtml = `<h3>Precision:</h3> ${data.precision}%`;
                document.getElementById('precisionContainer').innerHTML = precisionHtml;
            })
            .catch(error => {
                console.error('Error:', error);
            });
    });


    </script>




<div id="errorsContainer"></div>
<canvas id="errorChart" width="800" height="400"></canvas>


<div id="coordinates"></div>
<button type="button" class="btn btn-primary" id="showErrorsButton">
    Show Errors
</button>
<button type="button" class="btn btn-primary" id="testingButton">
    Run Testing
</button>
<script>
    var errorsList = @Html.Raw(Json.Serialize(Model.Errors));
    var canvas = document.getElementById('errorChart');
    var ctx = canvas.getContext('2d');
    var numEpochs = errorsList.length;

    ctx.beginPath();
    ctx.moveTo(50, 350); 
    ctx.lineTo(750, 350); 
    ctx.moveTo(50, 350); 
    ctx.lineTo(50, 50); 
    ctx.stroke();

    var scaledErrors = errorsList.map(function (error) {
        return error * 100; 
    });

    var maxError = Math.max.apply(null, scaledErrors);
    var yScale = 300 / maxError; 

    var xGap = 700 / numEpochs;

    for (var i = 0; i < numEpochs; i++) {
        var x = 50 +i * xGap; 
        var y = 350 - scaledErrors[i] * yScale; 
        ctx.beginPath();
        ctx.arc(x, y, 3, 0, 2 * Math.PI);
        ctx.fillStyle = 'red';
        ctx.fill();
    }
    canvas.addEventListener('click', function (event) {
        var rect = canvas.getBoundingClientRect();
        var mouseX = event.clientX - rect.left;
        var mouseY = event.clientY - rect.top;

        var xAxisValue = Math.floor((mouseX - 50) / xGap); 
        var yAxisValue = scaledErrors[xAxisValue]/100; 

        document.getElementById('coordinates').textContent = 'Epoch: ' + xAxisValue + ', Error: ' + yAxisValue;
    });
</script>





<script>
    function showNeuronDetails(inputValue, weights) {
    var parsedWeights = weights.map(function(weight) {
        if (typeof weight === 'string') {
            return parseFloat(weight.replace(',', '.')); 
        }
        return weight;
    });

    var weightsString = parsedWeights.join(', ');
    alert('Input (x): ' + inputValue + '\nWeights (w): ' + weightsString);
}
</script>

<script>
    document.getElementById('showErrorsButton').addEventListener('click', function () {
        var errorsList = @Html.Raw(Json.Serialize(Model.Errors));
        var errorsHtml = '<ul>';
        for (var i = 0; i < errorsList.length; i++) {
            errorsHtml += '<li>' + (i + 1) + '. Error: ' + errorsList[i] + '</li>';
        }
        errorsHtml += '</ul>';
        document.getElementById('errorsContainer').innerHTML = errorsHtml;
    });
</script>